# .streamlit/secrets.toml
[supabase]
url="https://tgogbyixtjaooxdqsjxh.supabase.co"
key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnb2dieWl4dGphb294ZHFzanhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjMzODMsImV4cCI6MjA2MTMzOTM4M30.ONRsDWeLvV7CIoD-WNtkiMSQQlbxDT0TL1n4TzZe1As"